name: Ash
pokemon: 
  xatu: ['dazzling gleam', 'peck', 'drill peck', 'quick attack']
  watchog: ['strength', 'seed bomb', 'slam', 'aqua tail']
  whimsicott': ['dazzling gleam', 'fairy wind', 'seed bomb']
  zeraora': ['brutal swing', 'plasma fists', 'quick attack', 'scratch']
  tangela': ['power whip', 'cut', 'seed bomb', 'slam']
  hydreigon: ['aqua tail', 'dragon pulse', 'hyper voice', 'brutal swing']
